version: '3.0'

services:
  app: &app
    build: ./
    image: frank/clique:latest
    command: bash -c "rm -f tmp/pids/server.pid && ./bin/dev"
    depends_on:
      - database
      - redis
    ports:
      - "3000:3000"
      - "4000:4000"
    volumes:
      - ./:/usr/src/app:cached
      - bundle_cache:/bundle_cache
    env_file:
      - ./.environments/development/web
      - ./.environments/development/database
    tty: true
    stdin_open: true
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack-dev-server
      - BUNDLE_PATH=/bundle_cache

  redis:
    image: redis
    command: [sh, -c, "rm -rf /data/dump.rdb && redis-server"]

  database:
    image: postgres:13
    ports:
      - 5433:5432
    env_file:
      - ./.environments/development/database
    volumes:
      - db_data:/var/lib/postgresql/data:cached

volumes:
  db_data:
  bundle_cache:
