#!/bin/bash

ZSHRC_FILE=~/.zshrc
if [ -f "$ZSHRC_FILE" ]; then
  echo "export PATH=\"${PWD/#$HOME/'$HOME'}/bin:\$PATH\"" >> ~/.zshrc
  source ~/.zshrc
else
  echo "export PATH=\"${PWD/#$HOME/'$HOME'}/bin:\$PATH\"" >> ~/.profile
  source ~/.profile
fi
